'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import Contacts from '@/components/about/Contacts';
import CodeSnippet from '@/components/about/codesnippets/CodeSnippet';
import ProfessionalFolders from '@/components/about/navigation/ProfessionalFolders';

export const metadata = {
  title: 'About | Nick Volokhin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, titleFile }) {
  const router = useRouter();
  return (
    <div className={`flex`}>
      <div className={`flex-col border-r-2 p-5 gap-y-8`} style={{ borderColor: '#1E2D3D' }}>
        <div className={`mb-7`}>
          <Link href="/professional" className={`opacity-100 hover:opacity-100 transition`}>
            <Image src={require('../../public/icons/professional.svg')} width={40} height={40} />
          </Link>
        </div>
        <div className={`mb-7`}>
          <Link href="/about" className={`opacity-40 hover:opacity-100 transition`}>
            <Image src={require('../../public/icons/personal.svg')} width={40} height={40} />
          </Link>
        </div>
        <div className={`mb-7`}>
          <Link href="/hobbies" className={`opacity-40 hover:opacity-100 transition`}>
            <Image src={require('../../public/icons/hobbies.svg')} width={40} height={40} />
          </Link>
        </div>
      </div>
      <div className={`border-r-2 w-3/12`} style={{ borderColor: '#1E2D3D' }}>
        <ProfessionalFolders />
        <Contacts />
      </div>
      <div className={`w-5/12`}>
        <div className={`flex-col`} style={{ width: '100%' }}>
          <div style={{ color: '#607B96' }}>{children}</div>
        </div>
      </div>
      <div className={`border-x-2 p-1 w-7`} style={{ borderColor: '#1E2D3D' }}></div>
      <div
        className={`py-5 px-10 w-6/12 overflow-y-scroll overflow-x-hidden scrollbar scrollbar-w-3 scrollbar-thumb-slate-500`}
        style={{ height: '800px' }}>
        <div className={`text-[#607B96]`}>// Code snippet showcase:</div>
        <CodeSnippet details="123" stars="3" created="1 month">
          {`export const abbreviate_number = (num, fixed) => {
  if (num === null) {
    return null;
  }
  if (num === 0) {
    return '0';
  }
  fixed = !fixed || fixed < 0 ? 0 : fixed;
  var b = num.toPrecision(2).split('e'),
    k = b.length === 1 ? 0 : 
    Math.floor(Math.min(b[1].slice(1), 14) / 3),
    c = k < 1 ? num.toFixed(0 + fixed) : (num / 
    Math.pow(10, k * 3)).toFixed(1 + fixed),
    d = c < 0 ? c : Math.abs(c), // enforce -0 is 0
    e = d + ['', 'K', 'M', 'B', 'T'][k]; // append power
  return e;
};
`}
        </CodeSnippet>
      </div>
      <div className={`border-x-2 p-1 w-7`} style={{ borderColor: '#1E2D3D' }}></div>
    </div>
  );
}
