'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import Contacts from '@/components/about/Contacts';
import PersonalFolders from '@/components/about/navigation/PersonalFolders';
import CodeSnippet from '@/components/about/codesnippets/CodeSnippet';

export const metadata = {
  title: 'About | Nick Volokhin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, titleFile }) {
  const router = useRouter();
  return (
    <div className={`flex`}>
      <div className={`flex-col border-r-2 p-5 gap-y-8`} style={{ borderColor: '#1E2D3D' }}>
        <div className={`mb-7`}>
          <Link href="/professional" className={`opacity-40 hover:opacity-100 transition`}>
            <Image src={require('../../public/icons/professional.svg')} width={40} height={40} />
          </Link>
        </div>
        <div className={`mb-7`}>
          <Link href="/about" className={`opacity-100 hover:opacity-100 transition`}>
            <Image src={require('../../public/icons/personal.svg')} width={40} height={40} />
          </Link>
        </div>
        <div className={`mb-7`}>
          <Link href="/hobbies" className={`opacity-40 hover:opacity-100 transition`}>
            <Image src={require('../../public/icons/hobbies.svg')} width={40} height={40} />
          </Link>
        </div>
      </div>
      <div className={`border-r-2 w-3/12`} style={{ borderColor: '#1E2D3D' }}>
        <PersonalFolders />
        <Contacts />
      </div>
      <div style={{ width: '50%' }}>
        <div className={`flex-col`}>
          <div style={{ color: '#607B96' }}>{children}</div>
        </div>
      </div>
      <div className={`border-x-2 p-1 w-7`} style={{ borderColor: '#1E2D3D' }}></div>
      <div
        className={`py-5 px-10 overflow-y-scroll overflow-x-hidden scrollbar scrollbar-w-3 scrollbar-thumb-slate-500`}
        style={{ height: '800px', width: '50%' }}>
        <div className={`text-[#607B96]`}>// Code snippet showcase:</div>
        <CodeSnippet details="123" stars="3" created="1 month">
          {`export const selectBalance = (state) => {
  const months = ['01', '02', '03', '04', '05',
   '06', '07', '08', '09', '10', '11', '12'];
  const balances = [];
  for (const month of months) {
    const balanceDeposit = state.balanceSlice.money
      .filter((item) => item.type === 'пополнение' 
      && item.date.slice(3, -5) === month)
      .reduce((acc, item) => acc + +item.sum, 0);
    const balanceWithdraw = state.balanceSlice.money
      .filter((item) => item.type === 'вывод' && 
      item.date.slice(3, -5) === month)
      .reduce((acc, item) => acc + +item.sum, 0);
    balances.push(balanceDeposit - balanceWithdraw);
  }
  return balances;
};
`}
        </CodeSnippet>
      </div>
      <div className={`border-x-2 p-1 w-7`} style={{ borderColor: '#1E2D3D' }}></div>
    </div>
  );
}
