'use client';
import AboutTitle from '@/components/about/AboutTitle';

export const metadata = {
  title: 'About | Nick Volokhin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, titleFile }) {
  return (
    <div className={`flex`}>
      <div className={`border-r-2 w-2/12`} style={{ borderColor: '#1E2D3D' }}>
        <AboutTitle title="projects" />
      </div>
      <div className={`flex-col`} style={{ width: '100%' }}>
        <div style={{ color: '#607B96' }}>{children}</div>
      </div>
    </div>
  );
}
