'use client';
import { useRouter } from 'next/navigation';
import Contacts from '@/components/about/Contacts';
import FindMe from '@/components/about/FindMe';
import { codeText } from '@/Helpers/codeText';

export const metadata = {
  title: 'About | Nick Volokhin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, titleFile }) {
  return (
    <div className={`flex`}>
      <div className={`border-r-2 w-3/12`} style={{ borderColor: '#1E2D3D' }}>
        <Contacts isContacts={true} />
        <FindMe />
      </div>
      <div className={`flex-col`} style={{ width: '100%' }}>
        <div style={{ color: '#607B96' }}>{children}</div>
      </div>
    </div>
  );
}
