'use client';

import Link from 'next/link';
import Image from 'next/image';
import Contacts from '@/components/about/Contacts';
import HobbiesFolders from '@/components/about/navigation/HobbiesFolders';

export const metadata = {
  title: 'About | Nick Volokhin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <div className={`flex`}>
      <div className={`flex-col border-r-2 p-5 gap-y-8`} style={{ borderColor: '#1E2D3D' }}>
        <div className={`mb-7`}>
          <Link href="/professional" className={`opacity-40 hover:opacity-100 transition`}>
            <Image alt='Professional' src={require('../../public/icons/professional.svg')} />
          </Link>
        </div>
        <div className={`mb-7`}>
          <Link href="/about" className={`opacity-40 hover:opacity-100 transition`}>
            <Image alt='Personal' src={require('../../public/icons/personal.svg')} />
          </Link>
        </div>
        <div className={`mb-7`}>
          <Link href="/hobbies" className={`opacity-1000 hover:opacity-100 transition`}>
            <Image alt='Hobbies' src={require('../../public/icons/hobbies.svg')} />
          </Link>
        </div>
      </div>
      <div className={`border-r-2`} style={{ borderColor: '#1E2D3D' }}>
        <HobbiesFolders />
        <Contacts />
      </div>
      <div>{children}</div>
    </div>
  );
}
